name: Test
on:
  pull_request:
    paths: [src/**/*.tsx]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm run test
